spring.application.name=holiday_receiver
server.port=8082
spring.kafka.bootstrap-servers=172.23.0.4:9092
spring.kafka.consumer.group-id=test-consumer-group
spring.kafka.consumer.auto-offset-reset=earliest